from datetime import datetime, timezone
from sqlalchemy import Float, Text, ForeignKey, DateTime
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Grade(Base):
    """
    Grading result for one SubmissionFile (one matched .ipynb notebook).

    score           — float 0–10 (per-file score, generated by the evaluator).
    feedback_text   — plain-English feedback referencing the actual submission.
    rationale_json  — structured criterion-by-criterion breakdown stored as a
                      JSON string:
                      [{"criterion": str, "points_possible": float,
                        "points_awarded": float, "explanation": str}, ...]
                      Persisted cheaply here now; the "why did I get this score"
                      chatbot query is an Extended Goal (Section 10).

    Re-grading overwrites the existing Grade row for the same submission_file_id
    (no versioning in MVP).
    """

    __tablename__ = "grades"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    submission_file_id: Mapped[int] = mapped_column(
        ForeignKey("submission_files.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,   # one Grade per SubmissionFile; re-grade replaces it
        index=True,
    )
    score: Mapped[float] = mapped_column(Float, nullable=False)
    feedback_text: Mapped[str] = mapped_column(Text, nullable=False)
    # Full JSON blob — criterion-level breakdown.
    rationale_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    graded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    submission_file: Mapped["SubmissionFile"] = relationship(  # noqa: F821
        "SubmissionFile", back_populates="grade"
    )

    def __repr__(self) -> str:
        return f"<Grade id={self.id} submission_file_id={self.submission_file_id} score={self.score}>"
